name: Go

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 23,0-12 * * *' # 8AM ~ 9PM KST
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Set up Environment Variables
      run: |
        echo "SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL" >> .env
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Preferences
      run: |
        go env -w GO111MODULE=auto
        go get github.com/joho/godotenv
    - name: Build and Run
      run: |
        go build -v main.go
        go run main.go
        
