name: Go

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 23,0-12 * * *' # 8AM ~ 9PM KST
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install dependencies
      run: |
        go get github.com/joho/godotenv
    - name: Build and Run
      run: go build -v main.go
